# SPDX-License-Identifier: LGPL-3.0-or-later
################################################################################
# shadowblox - https://git.seki.pw/Fumohouse/shadowblox
#
# Copyright 2025-present ksk.
# Copyright 2025-present shadowblox contributors.
#
# Licensed under the GNU Lesser General Public License version 3.0 or later.
# See COPYRIGHT.txt for more details.
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU Lesser General Public License as published by the Free
# Software Foundation, either version 3 of the License, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
# details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.
################################################################################


def generate_enums(api, header_path, source_path):
    enums = api["Enums"]

    header_lines = [
        "// shadowblox - https://git.seki.pw/Fumohouse/shadowblox",
        "// Autogenerated from Roblox API dump. Do not edit!",
        "#pragma once",
        "",
        '#include "Sbx/DataTypes/Enums.hpp"',
        '#include "Sbx/DataTypes/Enum.hpp"',
        "",
        "namespace SBX::DataTypes {",
        "",
        "template <typename T>",
        "struct EnumClassToEnum { static constexpr Enum *enumType = nullptr; };",
        "",
        "extern Enums enums;",
        "",
    ]

    source_lines = [
        "// shadowblox - https://git.seki.pw/Fumohouse/shadowblox",
        "// Autogenerated from Roblox API dump. Do not edit!",
        '#include "Sbx/DataTypes/EnumTypes.gen.hpp"',
        "",
        '#include "Sbx/DataTypes/Enums.hpp"',
        '#include "Sbx/DataTypes/Enum.hpp"',
        '#include "Sbx/DataTypes/EnumItem.hpp"',
        "",
        "namespace SBX::DataTypes {",
        "",
        "Enums enums;",
        "",
    ]

    for enum in enums:
        name = enum["Name"]
        items = enum["Items"]

        header_lines.append(f"// {name}")
        header_lines.append(f"extern Enum enum{name};")
        header_lines.append(f"enum class Enum{name} {{")

        for item in items:
            item_name = item["Name"]
            item_value = item["Value"]
            header_lines.append(f"\t{item_name} = {item_value},")

        header_lines.append("};")
        header_lines.append("")

        header_lines.append("template <>")
        header_lines.append(
            f"struct EnumClassToEnum<Enum{name}> {{ static constexpr Enum *enumType = &enum{name}; }};"
        )
        header_lines.append("")

        source_lines.append(f"// {name}")
        source_lines.append(f'Enum enum{name}("{name}", &enums);')

        for item in items:
            item_name = item["Name"]
            item_value = item["Value"]
            source_lines.append(
                f'static EnumItem enum{name}{item_name}("{item_name}", {item_value}, &enum{name});'
            )

        source_lines.append("")

    header_lines.append("} //namespace SBX::DataTypes")
    source_lines.append("} //namespace SBX::DataTypes")

    with open(header_path, "w") as f:
        f.write("\n".join(header_lines) + "\n")

    with open(source_path, "w") as f:
        f.write("\n".join(source_lines) + "\n")
