# SPDX-License-Identifier: MPL-2.0
################################################################################
# shadowblox - https://git.seki.pw/Fumohouse/shadowblox
#
# Copyright 2025-present ksk.
# Copyright 2025-present shadowblox contributors.
#
# This Source Code Form is subject to the terms of the Mozilla Public License,
# v. 2.0. If a copy of the MPL was not distributed with this file, You can
# obtain one at https://mozilla.org/MPL/2.0/.
#
# See COPYRIGHT.txt for more details.
################################################################################

def generate_enums(api, header_path, source_path):
    enums = api["Enums"]

    header_lines = [
        "// shadowblox - https://git.seki.pw/Fumohouse/shadowblox",
        "// Autogenerated from Roblox API dump. Do not edit!",
        "#pragma once",
        "",
        '#include "Sbx/DataTypes/Enums.hpp"',
        '#include "Sbx/DataTypes/Enum.hpp"',
        "",
        "namespace SBX::DataTypes {",
        "",
        "template <typename T>",
        "struct EnumClassToEnum { static constexpr Enum *enumType = nullptr; };",
        "",
        "extern Enums enums;",
        "",
    ]

    source_lines = [
        "// shadowblox - https://git.seki.pw/Fumohouse/shadowblox",
        "// Autogenerated from Roblox API dump. Do not edit!",
        '#include "Sbx/DataTypes/EnumTypes.gen.hpp"',
        "",
        '#include "Sbx/DataTypes/Enums.hpp"',
        '#include "Sbx/DataTypes/Enum.hpp"',
        '#include "Sbx/DataTypes/EnumItem.hpp"',
        "",
        "namespace SBX::DataTypes {",
        "",
        "Enums enums;",
        "",
    ]

    for enum in enums:
        name = enum["Name"]
        items = enum["Items"]

        header_lines.append(f"// {name}")
        header_lines.append(f"extern Enum enum{name};")
        header_lines.append(f"enum class Enum{name} {{")

        for item in items:
            item_name = item["Name"]
            item_value = item["Value"]
            header_lines.append(f"\t{item_name} = {item_value},")

        header_lines.append("};")
        header_lines.append("")

        header_lines.append("template <>")
        header_lines.append(
            f"struct EnumClassToEnum<Enum{name}> {{ static constexpr Enum *enumType = &enum{name}; }};"
        )
        header_lines.append("")

        source_lines.append(f"// {name}")
        source_lines.append(f'Enum enum{name}("{name}", &enums);')

        for item in items:
            item_name = item["Name"]
            item_value = item["Value"]
            source_lines.append(
                f'static EnumItem enum{name}{item_name}("{item_name}", {item_value}, &enum{name});'
            )

        source_lines.append("")

    header_lines.append("} //namespace SBX::DataTypes")
    source_lines.append("} //namespace SBX::DataTypes")

    with open(header_path, "w") as f:
        f.write("\n".join(header_lines) + "\n")

    with open(source_path, "w") as f:
        f.write("\n".join(source_lines) + "\n")
