// SPDX-License-Identifier: MPL-2.0
/*******************************************************************************
 * shadowblox - https://git.seki.pw/Fumohouse/shadowblox
 *
 * Copyright 2025-present ksk.
 * Copyright 2025-present shadowblox contributors.
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License,
 * v. 2.0. If a copy of the MPL was not distributed with this file, You can
 * obtain one at https://mozilla.org/MPL/2.0/.
 *
 * See COPYRIGHT.txt for more details.
 ******************************************************************************/

/*******************************************************************************
 * NOTE: This file is partially auto-generated by sbxcg. Modifications outside
 * BEGIN USER CODE <name> and END USER CODE comment blocks will be lost!
 * The sbxcg tool is present at the root of this project and can be invoked with
 * `python3 -m sbxcg`. See the developer documentation for more details.
 ******************************************************************************/

// SBXCG CLASS SOURCE Object
// clang-format off

#include "Sbx/Classes/Object.hpp" // NOLINT
#include "lua.h" // NOLINT

// clang-format on
/* BEGIN USER CODE PreNamespace */
#include <memory>
#include <string>

#include "lualib.h"

#include "Sbx/Classes/ClassDB.hpp"
#include "Sbx/DataTypes/RBXScriptSignal.hpp"
#include "Sbx/Runtime/Base.hpp"
#include "Sbx/Runtime/SignalEmitter.hpp"
/* END USER CODE PreNamespace */
// clang-format off

namespace SBX::Classes {

// clang-format on
/* BEGIN USER CODE PreClass */
Object::Object() :
		emitter(std::make_shared<SignalEmitter>()) {
}
/* END USER CODE PreClass */
// clang-format off

int Object::GetPropertyChangedSignal(lua_State *L) {
	// clang-format on
	/* BEGIN USER CODE MethodGetPropertyChangedSignal */
	Object *self = LuauStackOp<Object *>::Check(L, 1);
	const char *propName = lua_tostring(L, 2);

	const ClassDB::Property *prop = ClassDB::GetProperty(self->GetClassName(), propName);
	if (!prop || prop->changedSignal.empty()) {
		luaL_error(L, "%s is not a valid property name.", propName);
	}

	luaSBX_checkcapability(L, prop->readSecurity, "read", propName);
	self->PushSignal(L, prop->changedSignal, prop->readSecurity);
	return 1;
	/* END USER CODE MethodGetPropertyChangedSignal */
	// clang-format off
}

bool Object::IsA(const char *className) const {
	// clang-format on
	/* BEGIN USER CODE MethodIsA */
	return ClassDB::IsA(GetClassName(), className);
	/* END USER CODE MethodIsA */
	// clang-format off
}

// clang-format on
/* BEGIN USER CODE PostClass */
void Object::PushSignal(lua_State *L, std::string_view name, SbxCapability security) {
	LuauStackOp<DataTypes::RBXScriptSignal>::Push(L, DataTypes::RBXScriptSignal(emitter, std::string(name), security));
}
/* END USER CODE PostClass */
// clang-format off

} //namespace SBX::Classes

// clang-format on
/* BEGIN USER CODE PostNamespace */

/* END USER CODE PostNamespace */
// clang-format off
