// SPDX-License-Identifier: LGPL-3.0-or-later
/*******************************************************************************
 * shadowblox - https://git.seki.pw/Fumohouse/shadowblox
 *
 * Copyright 2025-present ksk.
 * Copyright 2025-present shadowblox contributors.
 *
 * Licensed under the GNU Lesser General Public License version 3.0 or later.
 * See COPYRIGHT.txt for more details.
 *
 * This program is free software: you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation, either version 3 of the License, or (at your option)
 * any later version.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 *
 * You should have received a copy of the GNU Lesser General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 ******************************************************************************/

/*******************************************************************************
 * NOTE: This file is partially auto-generated by sbxcg. Modifications outside
 * BEGIN USER CODE <name> and END USER CODE comment blocks will be lost!
 * The sbxcg tool is present at the root of this project and can be invoked with
 * `python3 -m sbxcg`. See the developer documentation for more details.
 ******************************************************************************/

// SBXCG CLASS SOURCE Object
// clang-format off

#include "Sbx/Classes/Object.hpp" // NOLINT
#include "lua.h" // NOLINT

// clang-format on
/* BEGIN USER CODE PreNamespace */
#include <memory>
#include <string>

#include "lualib.h"

#include "Sbx/Classes/ClassDB.hpp"
#include "Sbx/DataTypes/RBXScriptSignal.hpp"
#include "Sbx/Runtime/Base.hpp"
#include "Sbx/Runtime/SignalEmitter.hpp"
/* END USER CODE PreNamespace */
// clang-format off

namespace SBX::Classes {

// clang-format on
/* BEGIN USER CODE PreClass */
Object::Object() :
		emitter(std::make_shared<SignalEmitter>()) {
}
/* END USER CODE PreClass */
// clang-format off

int Object::GetPropertyChangedSignal(lua_State *L) {
	// clang-format on
	/* BEGIN USER CODE MethodGetPropertyChangedSignal */
	Object *self = LuauStackOp<Object *>::Check(L, 1);
	const char *propName = lua_tostring(L, 2);

	const ClassDB::Property *prop = ClassDB::GetProperty(self->GetClassName(), propName);
	if (!prop || prop->changedSignal.empty()) {
		luaL_error(L, "%s is not a valid property name.", propName);
	}

	luaSBX_checkcapability(L, prop->readSecurity, "read", propName);
	self->PushSignal(L, prop->changedSignal, prop->readSecurity);
	return 1;
	/* END USER CODE MethodGetPropertyChangedSignal */
	// clang-format off
}

bool Object::IsA(const char *className) const {
	// clang-format on
	/* BEGIN USER CODE MethodIsA */
	return ClassDB::IsA(GetClassName(), className);
	/* END USER CODE MethodIsA */
	// clang-format off
}

// clang-format on
/* BEGIN USER CODE PostClass */
void Object::PushSignal(lua_State *L, std::string_view name, SbxCapability security) {
	LuauStackOp<DataTypes::RBXScriptSignal>::Push(L, DataTypes::RBXScriptSignal(emitter, std::string(name), security));
}
/* END USER CODE PostClass */
// clang-format off

} //namespace SBX::Classes

// clang-format on
/* BEGIN USER CODE PostNamespace */

/* END USER CODE PostNamespace */
// clang-format off
